<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DashboardUsers70Post66Topics80</name>
   <tag></tag>
   <elementGuidId>6a465ca9-770e-45cd-b9eb-708c444b1fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pt-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>88c500ff-dad2-4ea0-833d-3704fa42ea7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pt-5</value>
      <webElementGuid>9471833d-9c5e-43c2-afe7-fc5a3ecc2d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DashboardUsers70Post66Topics80</value>
      <webElementGuid>85cf5d67-8b2c-4f25-a5bd-a30ddcb9d162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;flex w-full&quot;]/div[@class=&quot;pt-5&quot;]</value>
      <webElementGuid>05d76ba2-d000-4682-971f-54bcff8c2681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]</value>
      <webElementGuid>98285a3a-6cc9-4e12-8cf5-cd25afc6f35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[1]</value>
      <webElementGuid>8f335dc8-9908-41c7-8cd2-9fd9e0523542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Topic'])[1]/following::div[2]</value>
      <webElementGuid>930be6ea-9f30-4b8a-ac65-c5471090993e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>22660e41-c825-475a-813f-72f1394a21db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DashboardUsers70Post66Topics80' or . = 'DashboardUsers70Post66Topics80')]</value>
      <webElementGuid>88348a5c-cc52-484e-9d26-c9cbacc08b77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
